routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function(){

    Route::get('/', function () {
        $count['study_outcome'] = App\Models\StudyOutcome::count();
        $count['tahun_akademik'] = App\Models\TahunAkademik::count();
        $count['matakuliah'] = App\Models\Matakuliah::count();
        $count['dosen'] = App\Models\Dosen::count();
        $count['mahasiswa'] = App\Models\Mahasiswa::count();
        $count['ruang'] = App\Models\Ruang::count();        
        $count['jadwal'] = App\Models\Jadwal::count();
        $count['krs'] = App\Models\Krs::count();

        return view('dashboard', compact('count'));
    })->name('dashboard');    

    Route::group(['prefix' => 'dosen', 'as' => 'dosen.'], function () {
        Route::get('/', 'DosenController@index')->name('index');
        Route::post('/', 'DosenController@store')->name('store');    
        Route::get('/{id}/edit','DosenController@edit')->name('edit');
        Route::get('/data', 'DosenController@data')->name('data');     
        Route::put('/{id}', 'DosenController@update')->name('update'); 
        Route::delete('/{id}', 'DosenController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'mahasiswa', 'as' => 'mahasiswa.'], function () {
        Route::get('/', 'MahasiswaController@index')->name('index');
        Route::post('/', 'MahasiswaController@store')->name('store');    
        Route::get('/{id}/edit','MahasiswaController@edit')->name('edit');
        Route::get('/data', 'MahasiswaController@data')->name('data');
        Route::get('/{id}/study-outcome', 'MahasiswaController@study_outcome_index')->name('study-outcome.index');     
        Route::get('/{id}/study-outcome/pdf', 'MahasiswaController@study_outcome_pdf')->name('study-outcome.pdf');     
        Route::put('/{id}', 'MahasiswaController@update')->name('update'); 
        Route::delete('/{id}', 'MahasiswaController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'tahun-akademik', 'as' => 'tahun-akademik.'], function () {
        Route::get('/', 'TahunAkademikController@index')->name('index');
        Route::post('/', 'TahunAkademikController@store')->name('store');    
        Route::get('/{id}/edit','TahunAkademikController@edit')->name('edit');
        Route::get('/data', 'TahunAkademikController@data')->name('data');     
        Route::put('/{id}', 'TahunAkademikController@update')->name('update'); 
        Route::delete('/{id}', 'TahunAkademikController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'study-outcome', 'as' => 'study-outcome.'], function () {
        Route::get('/', 'StudyOutcomeController@index')->name('index');    
        Route::get('/data', 'StudyOutcomeController@data')->name('data');         
        Route::get('/{id}/edit','StudyOutcomeController@edit')->name('edit');
        Route::post('/', 'StudyOutcomeController@store')->name('store');    
        Route::put('/{id}', 'StudyOutcomeController@update')->name('update'); 
        Route::delete('/{id}', 'StudyOutcomeController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'matakuliah', 'as' => 'matakuliah.'], function () {
        Route::get('/', 'MatakuliahController@index')->name('index');    
        Route::get('/data', 'MatakuliahController@data')->name('data');
        Route::get('/{id}/edit','MatakuliahController@edit')->name('edit');
        Route::post('/', 'MatakuliahController@store')->name('store');    
        Route::put('/{id}', 'MatakuliahController@update')->name('update'); 
        Route::delete('/{id}', 'MatakuliahController@destroy')->name('destroy');  

        Route::get('/{matakuliah_id}/learning-outcome/pdf', 'LearningOutcomeController@pdf')->name('learning-outcome.pdf'); 
        Route::get('/{matakuliah_id}/learning-outcome', 'LearningOutcomeController@index')->name('learning-outcome.index'); 
        Route::group(['prefix' => '/learning-outcome', 'as' => 'learning-outcome.'], function () {
            Route::post('/', 'LearningOutcomeController@store')->name('store'); 
            Route::put('/{id}', 'LearningOutcomeController@update')->name('update'); 
            Route::delete('/{id}', 'LearningOutcomeController@destroy')->name('destroy');

            Route::group(['prefix' => '/assesment', 'as' => 'assesment.'], function () {
                Route::post('/', 'AssesmentController@store')->name('store'); 
                Route::put('/bobot', 'AssesmentController@bobot_bulk_update')->name('bobot.bulk.update');     
                Route::put('/{id}', 'AssesmentController@update')->name('update');
                Route::delete('/{id}', 'AssesmentController@destroy')->name('destroy');        
            });        
        });          

        Route::get('/{matakuliah_id}/nilai-assesment', 'NilaiAssesmentController@matakuliah')->name('nilai-assesment.index');
        Route::put('/{matakuliah_id}/nilai-assesment/nilai', 'NilaiAssesmentController@matakuliah_nilai_bulk_update')->name('nilai-assesment.nilai.bulk.update');    
        Route::get('/{matakuliah_id}/nilai-assesment/pdf', 'NilaiAssesmentController@matakuliah_pdf')->name('nilai-assesment.pdf');        
    });            

    Route::group(['prefix' => 'jadwal', 'as' => 'jadwal.'], function () {
        Route::get('/{jadwal_id}/nilai-assesment', 'NilaiAssesmentController@index')->name('nilai-assesment.index');
        Route::put('/{jadwal_id}/nilai-assesment/nilai', 'NilaiAssesmentController@nilai_bulk_update')->name('nilai-assesment.nilai.bulk.update');    
        Route::get('/{jadwal_id}/nilai-assesment/pdf', 'NilaiAssesmentController@pdf')->name('nilai-assesment.pdf');                
        
        Route::get('/', 'JadwalController@index')->name('index');
        Route::post('/', 'JadwalController@store')->name('store');    
        // Route::get('/{id}/edit','TahunAkademikController@edit')->name('edit');
        Route::get('/bulkdelete','JadwalController@bulkdelete')->name('jadwal.bulkdelete');
        Route::get('/{id}/select','JadwalController@select')->name('select');
        Route::get('/{idt}/{idk}/{ids}/getview', 'JadwalController@getview')->name('getview'); 
        Route::get('/data', 'JadwalController@data')->name('data'); 
        Route::put('/', 'JadwalController@bulkupdate')->name('bulkupdate'); 
        // Route::put('/{id}', 'JadwalController@update')->name('update'); 
        Route::delete('/{id}', 'TahunAkademikController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'ruang', 'as' => 'ruang.'], function () {
        Route::get('/', 'RuangController@index')->name('index');
        Route::post('/', 'RuangController@store')->name('store');    
        Route::get('/{id}/edit','RuangController@edit')->name('edit');
        Route::get('/data', 'RuangController@data')->name('data');     
        Route::put('/{id}', 'RuangController@update')->name('update'); 
        Route::delete('/{id}', 'RuangController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'krs', 'as' => 'krs.'], function () {
        Route::get('/', 'KrsController@index')->name('index');
        Route::post('/', 'KrsController@store')->name('store');    
        Route::get('/{id}/edit','KrsController@edit')->name('edit');
        Route::get('/data', 'KrsController@data')->name('data');     
        Route::put('/{id}', 'KrsController@update')->name('update'); 
        Route::delete('/{id}', 'KrsController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'detail-krs', 'as' => 'detail-krs.'], function () {
        Route::get('/', 'DetailkrsController@index')->name('index');
        Route::post('/', 'DetailkrsController@store')->name('store'); 
        Route::get('/{id}/pdf', 'DetailkrsController@pdf')->name('pdf');   
        Route::get('/{id}/edit','DetailkrsController@edit')->name('edit');
        Route::get('/data', 'DetailkrsController@data')->name('data');
        Route::get('/jadwal', 'DetailkrsController@jadwal')->name('jadwal'); 
        Route::get('/{id}', 'DetailkrsController@show')->name('show');
        Route::put('/{id}', 'DetailkrsController@update')->name('update'); 
        Route::delete('/', 'DetailkrsController@destroy')->name('destroy');        
    });

});

Route::get('pdf/print', function ()
        {
            return view('krs.print');
        });

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    protected $table = 'mahasiswa';
    protected $guarded = ['id'];

    public function program_studi()
    {
        return $this->belongsTo('App\Models\ProgramStudi');
    }  

    public function krs()
    {
    	return $this->hasMany('App\Models\Krs');
    }  

    public function detail_krs_()
    {
        return $this->hasManyThrough('App\Models\DetailKrs', 'App\Models\Krs');
    }     
}

resources/views/mahasiswa/index.blade.php
@extends('layouts.wrap')

@section('title', 'Mahasiswa')

@section('css-plugins')
    @parent
    <!-- Sweetalert Css -->
    <link href="plugins/sweetalert/sweetalert.css" rel="stylesheet" />
@endsection

@section('css-custom')
    @parent
@endsection

@section('css-bottom')
    @parent
@endsection


@section('content')
<section class="content">
    <div class="container-fluid">
        <button type="button" id="modal-options" class="btn bg-teal btn-block btn-lg waves-effect" onclick="addForm()">
            <i class="material-icons">add</i>
        </button>        
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            MAHASISWA
                        </h2> 
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable" id="mahasiswa-table" width="100%">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>NIM</th>
                                        <th>Nama Mahasiswa</th>
                                        <th>Alamat</th>                                        
                                        <th></th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>ID</th>                                      
                                        <th>NIM</th>
                                        <th>Nama Mahasiswa</th>
                                        <th>Alamat</th>                                        
                                        <th></th>
                                    </tr>
                                </tfoot>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <!-- Modal -->
      <div class="modal fade" id="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
              <form method="post" id="modal-form">
                {{csrf_field()}} {{method_field('post')}}
                <input type="hidden" name="id" id="id">                                                      
                <div class="row clearfix">                                
                  <div class="col-sm-12">
                      <div class="form-group form-float">
                          <div class="form-line">
                              <input type="text" class="form-control" id="nim" name="nim">
                              <label class="form-label">NIM</label>
                          </div>
                      </div>
                  </div>
                  <div class="col-sm-12">
                      <div class="form-group form-float">
                          <div class="form-line">
                              <input type="text" class="form-control" id="nama" name="nama">
                              <label class="form-label">Nama Mahasiswa</label>
                          </div>
                      </div>
                  </div>
                  <div class="col-sm-12">
                    <div class="form-group form-float">
                        <div class="form-line">
                            <textarea rows="4" class="form-control no-resize" id="alamat" name="alamat"></textarea>
                            <label class="form-label">Alamat</label>
                        </div>
                    </div>
                  </div>                 
                </div>
              </form>                
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
              <input type="submit" class="btn btn-primary" value="Simpan" id="action">
            </div>

          </div>
        </div>
      </div>  
      {{-- End Modal --}}
    </div>
</section>
@endsection

@section('script-plugins')
    @parent
    <!-- Jquery DataTable Plugin Js -->
    <script src="plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
    <script src="plugins/sweetalert/sweetalert.min.js"></script>
    <script src="plugins/autosize/autosize.js"></script>

    <!-- Moment Plugin Js -->
    <script src="plugins/momentjs/moment.js"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>    
@endsection

@section('script-custom')
    @parent
    <script src="js/pages/tables/jquery-datatable.js"></script>
    <script src="js/pages/ui/notifications.js"></script>
    <script src="js/pages/forms/basic-form-elements.js"></script>   
@endsection

@section('script-bottom')
    <script type="text/javascript">  
        $(document).ready(function(){
            var table = $('#mahasiswa-table').DataTable({
                processing : true,
                serverSide : true,
                ajax       : "{{ route('mahasiswa.data') }}",
                order      :  [[ 0, 'desc' ], ],  
                aLengthMenu: [[ 5, 10, 25, 50, -1 ], [ 5, 10, 25, 50, "All" ]],                              
                columns:[
                    {data: 'id', name: 'id', visible: false, searchable: false},                                 
                    {data: 'nim', name: 'nim'},
                    {data: 'nama', name: 'nama'},
                    {data: 'alamat', name: 'alamat'},                    
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            }) 

            $('#action').on('click',function () {
                var id = $('#id').val();
                if (save_method == 'add') url = "{{ url('mahasiswa') }}";
                else url = "{{ url('mahasiswa') . '/' }}" + id;
                $.ajax({
                    url:url,
                    type:'POST',
                    data:$('#modal-form').serialize(),
                    success:function (data) {
                        $('#modal-form')[0].reset();                        
                        table.ajax.reload();
                        $('#modal').modal('hide');
                        swal({
                            title: 'Berhasil!',
                            text: data.message,
                            type: 'success',
                            timer: '3000'
                        })                        
                    },
                    error:function (data) {
                        dataResponseJson = data.responseJSON;
                        errors = dataResponseJson.errors
                        $.each( errors , function( key, value ) {
                            $.notify({
                                // options
                                message: value
                            },{
                                // settings
                                type: 'danger',
                                z_index: 9999,
                                delay: 3000,
                                placement: {
                                    from: "top",
                                    align: "center"
                                },                                
                            });
                        });                       
                    }

                })
            })

    });

    var url='';
    function addForm() {
        save_method = "add";  
        $('#modal-form .form-group .form-line').removeClass('focused');          
        $('#modal').modal('show');
        $('#id').val("");
        $('#nim').val("");
        $('#nama').val("");
        $('#alamat').val("");        
        $('#alamat').css("height", "auto");        
        $('input[name=_method').val('POST');
        $('#modal-form')[0].reset();            
        $('#modal-title').text('Tambah Mahasiswa'); 
        $('#action').val('Simpan');                                                
    }     

    function editForm(id) {
        save_method="edit";
        $('#modal-form .form-group .form-line').addClass('focused');
        $('#modal').modal('show');
        $('input[name=_method').val('PUT');
        $('#modal-form')[0].reset();
        $('#modal-title').text('Edit Mahasiswa'); 
        $('#action').val('Update');               
        $.ajax({
            url:"{{url('mahasiswa')}}"+"/"+id+"/edit",
            type:"get",
            dataType:"JSON",
            success:function (data) {
                $('#id').val(data.id);
                $('#nim').val(data.nim);
                $('#nama').val(data.nama);
                $('#alamat').val(data.alamat);
            },
            error:function (errors){
                console.log(errors)
            }
        })      
    }

    function deleteData(id){
        var csrf_token = $('meta[name="csrf-token"]').attr('content');
        swal({
                title: "Apa Anda Yakin Akan Menghapus Data ini?",
                text:"Data yang sudah dihapus tidak bisa dikembalikan!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ya, Saya Yakin!",
                cancelButtonText: "Tidak!",
                closeOnConfirm: true,
                closeOnCancel: true 
            },
            function () {
                $.ajax({
                url : "{{ url('mahasiswa') }}" + '/' + id,
                type : "POST",
                data : {'_method' : 'DELETE', '_token' : csrf_token},
                success : function(data) {
                    swal({
                        title: 'Berhasil!',
                        text: data.message,
                        type: 'success',
                        timer: '3000'
                    })                
                    $('#mahasiswa-table').DataTable().ajax.reload();
                },
                error : function (data) {
                    dataResponseJson = data.responseJSON;
                    errors = dataResponseJson.errors
                    $.each( errors , function( key, value ) {
                        $.notify({
                            // options
                            message: value
                        },{
                            // settings
                            type: 'danger',
                            z_index: 9999,
                            delay: 3000,
                            placement: {
                                from: "top",
                                align: "center"
                            },                                
                        });
                    }); 
                }
              });
            }
        )
    }    
    </script>    
@endsection  

resources/views/mahasiswa/study-outcome-pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Study Outcome - {{ $mahasiswa_n['nim'] }} | {{ $mahasiswa_n['nama'] }}</title>
    <style>
        * {
            color: #222;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            font-size: 14px;
        }
        td, th {
            border: 1px solid #333;
            padding: 5px;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .bg-grey {
            background-color: #CFCFCF;
        }       
        .bg-sky-blue {
            background-color: #D0E4F5;
        }
        .mr-b-5 {
            margin-bottom: 5px;
        }
        .pad-8 {
            padding: 8px;
        }
        .w-14 {
            width: 14%;
        }
        .header {
            font-size: 16px; 
            line-height: 1.5;
            border-left: none;
        }        
    </style>
</head>
<body>
    <table class="bg-sky-blue">
        <tr>
            <th class="w-14 text-center" style="border-right: none">
                <img src="images/logo.png" alt="Logo" width="85px">
            </th>
            <th class="header">
                CAPAIAN PEMBELAJARAN LULUSAN (CPL) / STUDY OUTCOME <br>
                PROGRAM STUDI TEKNIK INDUSTRI <br>
                FAKULTAS TEKNIK - UNIVERSITAS JENDERAL ACHMAD YANI
            </th>            
        </tr>
    </table>
    <table class="table table-bordered">
            <tr class="bg-grey">
                <th>Nomor Induk Mahasiswa</th>
                <th>Nama Mahasiswa</th>
                <th>Total Matakuliah yg sudah diambil</th>
                <th>Total SKS Matakuliah yg sudah diambil</th>
            </tr>
            <tr>
                <td>{{ $mahasiswa_n['nim'] }}</td>
                <td>{{ $mahasiswa_n['nama'] }}</td>
                <td>{{ $mahasiswa_n['matakuliah_merge_']->count() }}</td>
                <td>{{ $mahasiswa_n['matakuliah_merge_']->sum('sks') }}</td>
            </tr>
        </table>
        <table class="table table-bordered">
            <tr class="bg-grey">
                <th colspan="5">Capaian Pembelajaran Lulusan (CPL) / Study Outcome</th>
                <th>Nilai SO</th>
            </tr>
            @foreach ($mahasiswa_n['study_outcome_']->sortByDesc('nilai') as $study_outcome)
                <tr>
                    <th colspan="5">
                        {{ $study_outcome['kode'] }} : 
                        {{ $study_outcome['deskripsi'] }}
                    </th>
                    <th rowspan="{{ $study_outcome['matakuliah_']->isNotEmpty() ? $study_outcome['matakuliah_']->count() + 2 : 2 }}"
                        class="text-center"
                        >
                        @isset($study_outcome['nilai'])
                            {{ round($study_outcome['nilai'], 2) }}                        
                        @endisset                        
                    </th>
                </tr>
                @if ($study_outcome['matakuliah_']->isNotEmpty())
                    <tr>
                        <td rowspan="{{ $study_outcome['matakuliah_']->count() + 1 }}"
                            >Matakuliah yg berkontribusi untuk {{ $study_outcome['kode'] }}
                        </td>
                        <th>Kode MK</th>
                        <th>Nama MK</th>
                        <th>SKS</th>
                        <th>Nilai MK untuk {{ $study_outcome['kode'] }}</th>
                    </tr>
                    @foreach ($study_outcome['matakuliah_'] as $matakuliah)
                        <tr>
                            <td>{{ $matakuliah['kode'] }}</td>
                            <td>{{ $matakuliah['nama'] }}</td>
                            <td>{{ $matakuliah['sks'] }}</td>
                            <td>{{ round($matakuliah['nilai'], 2) }}</td>
                        </tr>
                    @endforeach                    
                @else
                    <tr>
                        <td colspan="5">
                            Belum ada matakuliah yang diambil oleh {{ $mahasiswa_n['nama'] }} yang berkontribusi untuk {{ $study_outcome['kode'] }}
                        </td>
                    </tr>
                @endif
            @endforeach
        </table>   
    <p class="text-right" style="font-size: 13px">Dicetak Pada: {{ now()->format('d-m-Y H:i') }}</p>
</body>
</html>