routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function(){

    Route::get('/', function () {
        $count['study_outcome'] = App\Models\StudyOutcome::count();
        $count['tahun_akademik'] = App\Models\TahunAkademik::count();
        $count['matakuliah'] = App\Models\Matakuliah::count();
        $count['dosen'] = App\Models\Dosen::count();
        $count['mahasiswa'] = App\Models\Mahasiswa::count();
        $count['ruang'] = App\Models\Ruang::count();        
        $count['jadwal'] = App\Models\Jadwal::count();
        $count['krs'] = App\Models\Krs::count();

        return view('dashboard', compact('count'));
    })->name('dashboard');    

    Route::group(['prefix' => 'dosen', 'as' => 'dosen.'], function () {
        Route::get('/', 'DosenController@index')->name('index');
        Route::post('/', 'DosenController@store')->name('store');    
        Route::get('/{id}/edit','DosenController@edit')->name('edit');
        Route::get('/data', 'DosenController@data')->name('data');     
        Route::put('/{id}', 'DosenController@update')->name('update'); 
        Route::delete('/{id}', 'DosenController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'mahasiswa', 'as' => 'mahasiswa.'], function () {
        Route::get('/', 'MahasiswaController@index')->name('index');
        Route::post('/', 'MahasiswaController@store')->name('store');    
        Route::get('/{id}/edit','MahasiswaController@edit')->name('edit');
        Route::get('/data', 'MahasiswaController@data')->name('data');
        Route::get('/{id}/study-outcome', 'MahasiswaController@study_outcome_index')->name('study-outcome.index');     
        Route::get('/{id}/study-outcome/pdf', 'MahasiswaController@study_outcome_pdf')->name('study-outcome.pdf');     
        Route::put('/{id}', 'MahasiswaController@update')->name('update'); 
        Route::delete('/{id}', 'MahasiswaController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'tahun-akademik', 'as' => 'tahun-akademik.'], function () {
        Route::get('/', 'TahunAkademikController@index')->name('index');
        Route::post('/', 'TahunAkademikController@store')->name('store');    
        Route::get('/{id}/edit','TahunAkademikController@edit')->name('edit');
        Route::get('/data', 'TahunAkademikController@data')->name('data');     
        Route::put('/{id}', 'TahunAkademikController@update')->name('update'); 
        Route::delete('/{id}', 'TahunAkademikController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'study-outcome', 'as' => 'study-outcome.'], function () {
        Route::get('/', 'StudyOutcomeController@index')->name('index');    
        Route::get('/data', 'StudyOutcomeController@data')->name('data');         
        Route::get('/{id}/edit','StudyOutcomeController@edit')->name('edit');
        Route::post('/', 'StudyOutcomeController@store')->name('store');    
        Route::put('/{id}', 'StudyOutcomeController@update')->name('update'); 
        Route::delete('/{id}', 'StudyOutcomeController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'matakuliah', 'as' => 'matakuliah.'], function () {
        Route::get('/', 'MatakuliahController@index')->name('index');    
        Route::get('/data', 'MatakuliahController@data')->name('data');
        Route::get('/{id}/edit','MatakuliahController@edit')->name('edit');
        Route::post('/', 'MatakuliahController@store')->name('store');    
        Route::put('/{id}', 'MatakuliahController@update')->name('update'); 
        Route::delete('/{id}', 'MatakuliahController@destroy')->name('destroy');  

        Route::get('/{matakuliah_id}/learning-outcome/pdf', 'LearningOutcomeController@pdf')->name('learning-outcome.pdf'); 
        Route::get('/{matakuliah_id}/learning-outcome', 'LearningOutcomeController@index')->name('learning-outcome.index'); 
        Route::group(['prefix' => '/learning-outcome', 'as' => 'learning-outcome.'], function () {
            Route::post('/', 'LearningOutcomeController@store')->name('store'); 
            Route::put('/{id}', 'LearningOutcomeController@update')->name('update'); 
            Route::delete('/{id}', 'LearningOutcomeController@destroy')->name('destroy');

            Route::group(['prefix' => '/assesment', 'as' => 'assesment.'], function () {
                Route::post('/', 'AssesmentController@store')->name('store'); 
                Route::put('/bobot', 'AssesmentController@bobot_bulk_update')->name('bobot.bulk.update');     
                Route::put('/{id}', 'AssesmentController@update')->name('update');
                Route::delete('/{id}', 'AssesmentController@destroy')->name('destroy');        
            });        
        });          

        Route::get('/{matakuliah_id}/nilai-assesment', 'NilaiAssesmentController@matakuliah')->name('nilai-assesment.index');
        Route::put('/{matakuliah_id}/nilai-assesment/nilai', 'NilaiAssesmentController@matakuliah_nilai_bulk_update')->name('nilai-assesment.nilai.bulk.update');    
        Route::get('/{matakuliah_id}/nilai-assesment/pdf', 'NilaiAssesmentController@matakuliah_pdf')->name('nilai-assesment.pdf');        
    });            

    Route::group(['prefix' => 'jadwal', 'as' => 'jadwal.'], function () {
        Route::get('/{jadwal_id}/nilai-assesment', 'NilaiAssesmentController@index')->name('nilai-assesment.index');
        Route::put('/{jadwal_id}/nilai-assesment/nilai', 'NilaiAssesmentController@nilai_bulk_update')->name('nilai-assesment.nilai.bulk.update');    
        Route::get('/{jadwal_id}/nilai-assesment/pdf', 'NilaiAssesmentController@pdf')->name('nilai-assesment.pdf');                
        
        Route::get('/', 'JadwalController@index')->name('index');
        Route::post('/', 'JadwalController@store')->name('store');    
        // Route::get('/{id}/edit','TahunAkademikController@edit')->name('edit');
        Route::get('/bulkdelete','JadwalController@bulkdelete')->name('jadwal.bulkdelete');
        Route::get('/{id}/select','JadwalController@select')->name('select');
        Route::get('/{idt}/{idk}/{ids}/getview', 'JadwalController@getview')->name('getview'); 
        Route::get('/data', 'JadwalController@data')->name('data'); 
        Route::put('/', 'JadwalController@bulkupdate')->name('bulkupdate'); 
        // Route::put('/{id}', 'JadwalController@update')->name('update'); 
        Route::delete('/{id}', 'TahunAkademikController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'ruang', 'as' => 'ruang.'], function () {
        Route::get('/', 'RuangController@index')->name('index');
        Route::post('/', 'RuangController@store')->name('store');    
        Route::get('/{id}/edit','RuangController@edit')->name('edit');
        Route::get('/data', 'RuangController@data')->name('data');     
        Route::put('/{id}', 'RuangController@update')->name('update'); 
        Route::delete('/{id}', 'RuangController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'krs', 'as' => 'krs.'], function () {
        Route::get('/', 'KrsController@index')->name('index');
        Route::post('/', 'KrsController@store')->name('store');    
        Route::get('/{id}/edit','KrsController@edit')->name('edit');
        Route::get('/data', 'KrsController@data')->name('data');     
        Route::put('/{id}', 'KrsController@update')->name('update'); 
        Route::delete('/{id}', 'KrsController@destroy')->name('destroy');        
    });

    Route::group(['prefix' => 'detail-krs', 'as' => 'detail-krs.'], function () {
        Route::get('/', 'DetailkrsController@index')->name('index');
        Route::post('/', 'DetailkrsController@store')->name('store'); 
        Route::get('/{id}/pdf', 'DetailkrsController@pdf')->name('pdf');   
        Route::get('/{id}/edit','DetailkrsController@edit')->name('edit');
        Route::get('/data', 'DetailkrsController@data')->name('data');
        Route::get('/jadwal', 'DetailkrsController@jadwal')->name('jadwal'); 
        Route::get('/{id}', 'DetailkrsController@show')->name('show');
        Route::put('/{id}', 'DetailkrsController@update')->name('update'); 
        Route::delete('/', 'DetailkrsController@destroy')->name('destroy');        
    });

});

Route::get('pdf/print', function ()
        {
            return view('krs.print');
        });

app/Models/Ruang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ruang extends Model
{
    protected $table = 'ruang';
    protected $guarded = ['id'];    

    public function jadwal()
    {
        return $this->hasMany('App\Models\Jadwal');
    }    
}

app/Http/Controllers/RuangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Validation\Rule;
use Illuminate\Http\Request;
use App\Models\Ruang;
use DataTables;
use Validator;

class RuangController extends Controller
{
    public function index()
    {
        return view('ruang.index');
    }

    public function store(Request $request)
    {        
        $validation = Validator::make($request->all(), [
            'nama' => 'required|unique',           
            'kapasitas' => 'required',
        ]);
          
        if ($validation->passes())
        {
            $ruang = Ruang::create([
                'nama' => $request->nama,           
                'kapasitas' => $request->kapasitas,         
            ]);
    
            return response()->json([
                'data'    => $ruang,
                'message' => 'Data Ruang berhasil ditambah',
            ], 201);
        }   

        return response()->json([
            'errors'  => $validation->errors()->all(),
        ], 422);  
    }  
    
    public function edit($id)
    {
        $ruang=Ruang::find($id);
        return $ruang;
    }

    public function update(Request $request, $id)
    {
        $ruang = Ruang::findOrFail($id);

        // $validation = Validator::make($request->all(), [
        //     'kode' => [
        //         'required',
        //         Rule::unique('fakultas')->ignore($fakultas->id),
        //     ],           
        //     'nama' => 'required',
        // ]);        
        
        // if ($validation->passes())
        // {
            $ruang->update([
                'nama' => $request->nama,           
                'kapasitas' => $request->kapasitas,         
            ]);
    
            return response()->json([
                'data'    => $ruang,
                'message' => 'Data Ruang berhasil diupdate',                
            ]);
        // }   

        // return response()->json([
        //     'errors'  => $validation->errors()->all(),
        // ], 422);         
    }

    public function destroy($id)
    {
        $ruang = Ruang::findOrFail($id);

        $ruang->delete();
        return response()->json([
            'message' => 'Data Ruang berhasil dihapus'
        ]);

    }

    public function data()
    {
        $ruang = Ruang::query();

        return DataTables::of($ruang)
            ->addColumn('action', function($ruang){
                return  '<a id="'.$ruang->id.'" onclick="editForm('.$ruang->id.')" class="btn btn-info waves-effect"><i class="material-icons">mode_edit</i></a> '.
                        '<a id="'.$ruang->id.'" onclick="deleteData('.$ruang->id.')" class="btn btn-danger waves-effect"><i class="material-icons">delete</i></a>';
            })        
            ->make(true);        
    }    
}

resources/views/ruang/index.blade.php
@extends('layouts.wrap')

@section('title', 'Ruang')

@section('css-plugins')
    @parent
    <!-- Sweetalert Css -->
    <link href="plugins/sweetalert/sweetalert.css" rel="stylesheet" />
@endsection

@section('css-custom')
    @parent
@endsection

@section('css-bottom')
    @parent
@endsection


@section('content')
<section class="content">
    <div class="container-fluid">
        <button type="button" id="modal-options" class="btn bg-teal btn-block btn-lg waves-effect" onclick="addForm()">
            <i class="material-icons">add</i>
        </button>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            RUANGAN
                        </h2> 
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable" id="ruang-table" width="100%">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nama</th>
                                        <th>Kapasitas</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>ID</th>                                      
                                        <th>Nama</th>
                                        <th>Kapasitas</th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <!-- Modal -->
      <div class="modal fade" id="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
              <div class="row clearfix">
                <form method="post" id="modal-form">
                  {{csrf_field()}} {{method_field('post')}}
                  <input type="hidden" name="id" id="id">                  
                  <div class="col-sm-12">
                      <div class="form-group form-float">
                          <div class="form-line">
                              <input type="text" class="form-control" id="nama" name="nama">
                              <label class="form-label">Nama Ruang</label>
                          </div>
                      </div>
                  </div>
                  <div class="col-sm-12">
                      <div class="form-group form-float">
                          <div class="form-line">
                              <input type="text" class="form-control" id="kapasitas" name="kapasitas">
                              <label class="form-label">Kapasitas Ruang</label>
                          </div>
                      </div>
                  </div>
                </form>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
              <input type="submit" class="btn btn-primary" value="Simpan" id="action">
            </div>

          </div>
        </div>
      </div>  
      {{-- End Modal --}}
    </div>
</section>
@endsection

@section('script-plugins')
    @parent
    <!-- Jquery DataTable Plugin Js -->
    <script src="plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
    <!-- SweetAlert Plugin Js -->
    <script src="plugins/sweetalert/sweetalert.min.js"></script>
@endsection

@section('script-custom')
    @parent
    <script src="js/pages/tables/jquery-datatable.js"></script>
    <script src="js/pages/ui/notifications.js"></script>
@endsection

@section('script-bottom')
    <script type="text/javascript">  
        $(document).ready(function(){
            var table = $('#ruang-table').DataTable({
                processing : true,
                serverSide : true,
                ajax       : "{{ route('ruang.data') }}",
                order      :  [[ 0, 'desc' ], ],  
                aLengthMenu: [[ 5, 10, 25, 50, -1 ], [ 5, 10, 25, 50, "All" ]],                              
                columns:[
                    {data: 'id', name: 'id', visible: false, searchable: false},                                 
                    {data: 'nama', name: 'nama'},
                    {data: 'kapasitas', name: 'kapasitas'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            }) 

            $('#action').on('click',function () {
                var id = $('#id').val();
                if (save_method == 'add') url = "{{ url('ruang') }}";
                else url = "{{ url('ruang') . '/' }}" + id;
                $.ajax({
                    url:url,
                    type:'POST',
                    data:$('#modal-form').serialize(),
                    success:function (data) {
                        $('#modal-form')[0].reset();                        
                        table.ajax.reload();
                        $('#modal').modal('hide');
                        swal({
                            title: 'Berhasil!',
                            text: data.message,
                            type: 'success',

                        })                        
                    },
                    error:function (data) {
                        dataResponseJson = data.responseJSON;
                        errors = dataResponseJson.errors
                        $.each( errors , function( key, value ) {
                            $.notify({
                                // options
                                message: value
                            },{
                                // settings
                                type: 'danger',
                                z_index: 9999,
                                delay: 3000,
                                placement: {
                                    from: "top",
                                    align: "center"
                                },                                
                            });
                        });                       
                    }

                })
            })

    });

    var url='';
    function addForm() {
        save_method = "add";  
        $('#modal-form .form-group .form-line').removeClass('focused');          
        $('#modal').modal('show');
        $('#id').val("");
        $('#kode').val("");
        $('#nama').val("");
        $('input[name=_method').val('POST');
        $('#modal-form')[0].reset();            
        $('#modal-title').text('Tambah Ruang'); 
        $('#action').val('Simpan');                                                
    }     

    function editForm(id) {
        save_method="edit";
        $('#modal-form .form-group .form-line').addClass('focused');
        $('#modal').modal('show');
        $('input[name=_method').val('PUT');
        $('#modal-form')[0].reset();
        $('#modal-title').text('Edit Ruang'); 
        $('#action').val('Update');               
        $.ajax({
            url:"{{url('ruang')}}"+"/"+id+"/edit",
            type:"get",
            dataType:"JSON",
            success:function (data) {
                $('#id').val(data.id);
                $('#nama').val(data.nama);
                $('#kapasitas').val(data.kapasitas);
            }
        })      
    }

    function deleteData(id){
        var csrf_token = $('meta[name="csrf-token"]').attr('content');
        swal({
                title: "Apa Anda Yakin Akan Menghapus Data ini?",
                text:"Data yang sudah dihapus tidak bisa dikembalikan!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ya, Saya Yakin!",
                cancelButtonText: "Tidak!",
                closeOnConfirm: true,
                closeOnCancel: true 
            },
            function () {
                $.ajax({
                url : "{{ url('ruang') }}" + '/' + id,
                type : "POST",
                data : {'_method' : 'DELETE', '_token' : csrf_token},
                success : function(data) {
                    swal({
                        title: 'Berhasil!',
                        text: data.message,
                        type: 'success',
                        timer: '3000'
                    })                
                    $('#ruang-table').DataTable().ajax.reload();
                },
                error : function (data) {
                    dataResponseJson = data.responseJSON;
                    errors = dataResponseJson.errors
                    $.each( errors , function( key, value ) {
                        $.notify({
                            // options
                            message: value
                        },{
                            // settings
                            type: 'danger',
                            z_index: 9999,
                            delay: 3000,
                            placement: {
                                from: "top",
                                align: "center"
                            },                                
                        });
                    }); 
                }
              });
            }
        )
    }    
    </script>    
@endsection  